### ISSUE TITLE
Feat: 검색 기능 추가 수정(관심상품 등록 체크)

### ISSUE THREAD

**Issue by devSojoong** [fastcampus-mini/credit-market-BE#25]
## Description

- 응답 값에 금리유형과 관심상품 등록 여부 값 전달하도록 추가함.
- 비회원인 경우에는 모든 상품이 조건에 맞게 or 조건이 없으면 전체 상품을 return 하도록 하고 관심상품 등록 여부가 false 로 return 됨.
- 회원인 경우에는 모든 상품이 조건에 맞게 or 조건이 없으면 전체 상품을 return 하도록 하고 로그인한 유저 별 관심상품 등록 여부가 return 됨.(true or false)

- 키워드 조건 컬럼
    - 금융 회사명
    - 금융 상품명
    - 대출 종류명
    - 금리 구분
- 카테고리 컬럼
    - 대출 종류 (마이너스한도대출, 신용대출, 일반신용대출, 장기카드대출(카드론))
    - 최소 나이 (10, 20, 30, 40)
    - 대상 성별 (여, 남)
    - 금리 유형 (default 값이 '대출금리' 로 추가 되었음. / 가감조정금리, 가산금리, 기준금리, 대출금리)
    - 평균 금리 (파라미터로 전달 받은 평균 금리 값 기준 이하로 검색된다.)

## Tasks

- [ ] 비회원 로직 처리(메인화면 접근 시 상품 리스트업)
- [ ] 회원 로직 처리(관심상품 등록 여부 return)
- [ ] Response 값 추가.(금리유형, 관심상품 등록 여부)
- [ ] 카테고리의 금리유형의 default value 를 "" 이 아닌 "대출금리" 로 값 수정.
