### ISSUE TITLE
Feat: 상품 구매 리스트로 받기

### ISSUE THREAD

**Issue by JeYeongR** [fastcampus-mini/credit-market-BE#50]
## Description

상품 구매 리스트로 받기

## Tasks

- [x] 리스트 DTO 생성
- [x] 컨트롤러 파라미터 및 api 수정
- [x] 상품 구매 로직 수정
